version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: d2l_extension_db
    user: root  
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Hq07092005@
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql/data
    restart: always

volumes:
  sqlvolume: